// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo4p_1GD6O7ZefdONw84U3tRDjDW2gPmE',
    appId: '1:252665621330:web:8db126c79007889c52288b',
    messagingSenderId: '252665621330',
    projectId: 'twitter-clone-f8b9d',
    authDomain: 'twitter-clone-f8b9d.firebaseapp.com',
    storageBucket: 'twitter-clone-f8b9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQ_lZ7MN8-_wSUBZQ9D5ERekFGdTzkQQ',
    appId: '1:252665621330:android:9f3911d1e8a9bcc252288b',
    messagingSenderId: '252665621330',
    projectId: 'twitter-clone-f8b9d',
    storageBucket: 'twitter-clone-f8b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFya46ZvM913yQZSYt-_VKu0cujxtbFw',
    appId: '1:252665621330:ios:87b44a8f24ab7a0c52288b',
    messagingSenderId: '252665621330',
    projectId: 'twitter-clone-f8b9d',
    storageBucket: 'twitter-clone-f8b9d.firebasestorage.app',
    iosBundleId: 'com.example.dentalRecap',
  );
}
